#!/bin/sh
if hash python 2>/dev/null; then
	exec python -c 'import pty, sys; sys.exit(pty.spawn(sys.argv[1:]))' "$@"
else
	if [[ "$OSTYPE" == "darwin"* ]]; then
		#exec script -q "$@" /dev/null #"$(printf "'%s' " "$@")"
		exec script -q /dev/null "$@"#"$(printf "'%s' " "$@")"
	else
		exec script -qfec "$(printf "'%s' " "$@")" /dev/null
	fi
fi
