#!/bin/bash
if  [[ "$OSTYPE" == "darwin"* ]]; then
	#exec script -q "$@" /dev/null #"$(printf "'%s' " "$@")"
	exec script -q /dev/null "$@"#"$(printf "'%s' " "$@")"
else
	exec script -qc "$(printf "'%s' " "$@")" /dev/null
fi
